- name: Ensure flatpak is installed
  ansible.builtin.package:
    name: flatpak
    state: present

# --- REPOSITORY SETUP ---

- name: Add the Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: system
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Add the Fedora Flatpak repository
  community.general.flatpak_remote:
    name: fedora
    state: present
    method: system
    flatpakrepo_url: oci+https://registry.fedoraproject.org

# --- INSTALLATION SECTIONS ---

- name: Install packages from Flathub
  community.general.flatpak:
    name:
      - app.zen_browser.zen
      - com.bambulab.BambuStudio
      - com.brave.Browser
      - com.collaboraoffice.Office
      - com.github.polymeilex.neothesia
      - com.github.wwmm.easyeffects
      - com.moonlight_stream.Moonlight
      - com.ranfdev.DistroShelf
      - com.usebottles.bottles
      - dev.lizardbyte.app.Sunshine
      - fr.handbrake.ghb
      - fr.romainvigier.MetadataCleaner
      - io.anytype.anytype
      - io.ente.auth
      - io.github.CyberTimon.RapidRAW
      - io.github.flattool.Warehouse
      - io.github.peazip.PeaZip
      - io.podman_desktop.PodmanDesktop
      - it.mijorus.gearlever
      - me.timschneeberger.jdsp4linux
      - net.ankiweb.Anki
      - net.lutris.Lutris
      - net.xmind.XMind
      - org.fcast.Receiver
      - org.gnome.Evince
      - org.gnome.Firmware
      - org.gnome.Maps
      - org.gnome.Snapshot
      - org.gnome.Weather
      - org.gnome.World.PikaBackup
      - org.gnome.design.IconLibrary
      - org.kde.CrowTranslate
      - org.kde.cantor
      - org.kde.drawy
      - org.kde.francis
      - org.kde.glaxnimate
      - org.kde.haruna
      - org.kde.itinerary
      - org.kde.kalk
      - org.kde.kalm
      - org.kde.kdenlive
      - org.kde.kid3
      - org.kde.kodaskanna
      - org.kde.krita
      - org.kde.kst
      - org.kde.labplot
      - org.kde.merkuro
      - org.kde.tellico
      - org.keepassxc.KeePassXC
      - org.localsend.localsend_app
      - org.nicotine_plus.Nicotine
      - org.qbittorrent.qBittorrent
      - org.vanillaos.ApxGUI
      - org.vinegarhq.Sober
      - tv.kodi.Kodi
    state: present
    method: system
    remote: flathub

- name: Install packages from Fedora Repo
  community.general.flatpak:
    name:
      - org.clementine_player.Clementine
      - org.gnome.Evolution
      - org.gnome.Meld
      - org.kde.rocs
    state: present
    method: system
    remote: fedora